version: '3.9'

services:
  notebook:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
    - ./projects:/projects
    - .cache:/.cache
    ports: 
    - 8888:8888